default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "Martial@5009" } %>

development:
  <<: *default
  database: Recipe_App_development
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "Martial@5009" } %>


test:
  <<: *default
  database: Recipe_App_test
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "Martial@5009" } %>

production:
  <<: *default
  database: Recipe_App_production
  username: Recipe_App
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
